### ISSUE TITLE
As a User I want to see my new ranking on the ladder after I submit a result for a game

### ISSUE THREAD

**Issue by DanielLarsenNZ** [DanielLarsenNZ/gameon#1]

**Comment by DanielLarsenNZ** [comment]
Backend will be implemented by #72

**Comment by olafwrieden** [comment]
Fantastic work @ncostar and @DanielLarsenNZ! Leave this one In Progress and remove the 'backend' tag once merged. I'll pick it up on the frontend. Soon we can close this # 1 with which it all started 😃 Yay!!
