### ISSUE TITLE
As a User I want to view the tournaments that are underway within the organisation

### ISSUE THREAD

**Issue by DanielLarsenNZ** [DanielLarsenNZ/gameon#3]

**Comment by olafwrieden** [comment]
@DanielLarsenNZ I've given this some thought and think this might be a nice way to display the tournament overview. Any feedback from your end?
![Overview](https://i.imgur.com/9gqe6Wn.png)

**Comment by DanielLarsenNZ** [comment]
OMG :shipit: ❤❤❤

**Comment by DanielLarsenNZ** [comment]
@olafwrieden The API has changed somewhat to match the DAPR state API. I now include a `tenantId` in all tournament paths. More details in `api.md`

**Comment by olafwrieden** [comment]
Added Tournaments View
