### ISSUE TITLE
As an Owner I want to be able to submit tournament rules so that players know the official regulations

### ISSUE THREAD

**Issue by olafwrieden** [DanielLarsenNZ/gameon#41]
The idea here is that rules show up on the tournament page's overview (below the description). Entering these by hand may get messy and doesn't scale, therefore:

@DanielLarsenNZ I recommend we allow the owner to enter a URL link to a website / YouTube video that contains the sport's ruleset... and simply store this as a String (nullable) for each tournament.

**Comment by DanielLarsenNZ** [comment]
Great idea!
