### ISSUE TITLE
Given no tournament exists in the tenant, when all tournaments are requested, an empty array should be returned.

### ISSUE THREAD

**Issue by olafwrieden** [DanielLarsenNZ/gameon#42]
@DanielLarsenNZ - Just pulled my hair out as to why I was getting error `204 - No Content` on `GET /tournaments`. Isn't a 200 response with an empty array more suited in this scenario?

Given no tournaments exist for the tenant, when `GET /tournaments` is called, then we should get a `200 - OK` and empty array because we are not saying it is an error that no data exists, there is just nothing there (hence `[]`).

**Comment by DanielLarsenNZ** [comment]
On it
