### ISSUE TITLE
As an Operator I want the client webapp to be published to prod every time there is a commit to main branch, client folder

### ISSUE THREAD

**Issue by DanielLarsenNZ** [DanielLarsenNZ/gameon#44]

**Comment by DanielLarsenNZ** [comment]
* [ ] publish.ps1
* [ ] Publish web GitHub Action
* [ ] Azure FrontDoor
* [ ] Custom DNS: gameon.nz
* [ ] Custom SSL: gameon.nz

**Comment by DanielLarsenNZ** [comment]
@dylan-apera - here is an overview of GitHub actions: https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions

This is an example that deploys the backend services https://github.com/DanielLarsenNZ/gameon/blob/main/.github/workflows/dotnet.yml

What we need is a new workflow called "client-spa.yml" that runs `./deploy/publish-web.ps1` script. The structure of the workflow is something like this:

```
Job
  Step "build"
    actions/checkout@v2  # Checkout the repo
    Azure/login@v1.1        # Login to Azure
    Azure/cli@1.0.4            # Run the publish-web.ps1 script
```

**Comment by dylan-apera** [comment]
@DanielLarsenNZ  - given the github actions a go but not 100% sure if it is doing what we need it to do.

Resources: https://github.com/Azure/login

**Comment by DanielLarsenNZ** [comment]
Will create a new issue for the HTTPS items. Well done @dylan-apera ! Thank you for your contribution 🎉
