### ISSUE TITLE
Bug: Actions runs build-and-deploy on Push to Feature Branches and Pull Requests

### ISSUE THREAD

**Issue by olafwrieden** [DanielLarsenNZ/gameon#50]
Discovered a bug in our build-and-deploy GitHub Actions and thought I'd escalate to our newly formed ops team to resolve, rather than doing it myself 🤣 @dylan-apera I'll let you think about what might be happening based on the two findings I am about to report. Test if you can resolve them without scrolling beyond this description. My only comment below documents the two changes we need to perform.

1. I was working on a feature branch and the Deploy Web App action was triggered with every push, this should not happen unless and until I push to `main` as it will break the production build.
2. After finishing development on the feature branch, I created a pull request and saw that it began firing again.. building and deploying the app as part of the automated 'CI checks' before I could merge the PR. This should also not happen until the PR is merged to `main` (see screenshot below).

@dylan-apera @DanielLarsenNZ Please take a look at the Deploy Web App action you put together on Monday, and ensure it only triggers a build and deploy once code has merged to `main`, not when commits are made to other branches, or PRs are created/updated. Beware that the same bug may exist in the .NET action too.

<img width="1233" alt="Build and Deploy on PR" src="https://user-images.githubusercontent.com/42084239/109812811-41652700-7c78-11eb-9fbe-f58446263176.png">

**Comment by olafwrieden** [comment]
Hint to the ops team: Check line 5 in [client-spa.yml](https://github.com/DanielLarsenNZ/gameon/blob/7c3ee80da823b248c535fc56552ff4703fff05a6/.github/workflows/client-spa.yml#L5) which lists the branch name in `[ main ]` - this is incorrect.

**Incorrect Syntax**
As currently used in file.
```yml
on:
  push:
    branches: [main]
    paths:
      - "client/**"
...
```

**Correct Syntax**
Read more: [Source](https://dev.to/github/running-github-actions-ci-cd-triggers-on-specific-branches-5e6m)
```yml
on:
  push:
    branches:
    - main
    paths:
      - "client/**"
...
```
Branches have to be specified using the above notation. The `[ ... ]` bracket notation can be used to group multiple triggers such as the following, not to be confused with multiple branch names in an array.
```yml
on: [push, pull_request]
```

In the client-spa.yml, completely remove all mention of the `pull_request` trigger (line 8-11) to resolve the second issue referenced in the issue description above. Merges to `main` (via PR or otherwise) are the only time we trigger the deployment workflow, this is a `push` event - no need for the additional `pull_request` trigger.

**Comment by dylan-apera** [comment]
Issue resolved
