### ISSUE TITLE
/auth page

### ISSUE THREAD

**Issue by DanielLarsenNZ** [DanielLarsenNZ/gameon#53]
@olafwrieden would you mind making an undocumented /auth page that we can hit (once we have logged in) to get a bearer token to use with our Rest API client please? Or you could give us a function in the F12 developer tools console that we could run, e.g. `getToken()`

**Comment by olafwrieden** [comment]
No worries mate, spent 20 minutes and have it up and running at [https://gameon.nz/developer](https://localhost:3000/developer). However, there was an error in the deployment action ([see here](https://github.com/DanielLarsenNZ/gameon/runs/2172643940)) which prevented this change from being deployed. Not sure what's going on 🤷🏻‍♂️ 

**Once deployed**
You can navigate to the page and are presented with a sign in button if you aren't signed in already. From there I've included a button to copy the token to the clipboard for you to paste in the REST client. 😄

**Using REST Client Directly**
Also found this in case it is helpful for connecting directly from the extension: [Use VSCode REST Client plugin with OAuth and Azure Active Directory](https://mobilefirstcloudfirst.net/2019/09/use-vscode-rest-client-plugin-oauth-azure-active-directory/) in case you want to bypass the frontend completely.

**Comment by DanielLarsenNZ** [comment]
I reran the action and the deployment worked! the developer page is amazing! 🤩 Thank you so much
